# file: diffapi-unbuntu2004.yml
# This calls into the build-native.yml template to build/test for x64 on ubuntu2004.
trigger:
  branches:
    include:
    - user/*
  paths:
    include:
    - src
    - pipelines/ci/diffapi-ubuntu2004.yml
    - pipelines/templates/build-native-linux.yml
    - pipelines/templates/build-managed-linux.yml

schedules:
- cron: "0 8 * * *"
  displayName: Midnight Build
  branches:
    include:
    - main
    - dev
  always: true

pool:
  vmImage: ubuntu-20.04

variables:
- name: EnableDetectorVcpkg
  value: true
- template: /pipelines/variables/common-variables.yml@self

steps:
  - template: /pipelines/variables/show-version-variables.yml@self

  - template: /pipelines/templates/build-native-linux.yml@self
    parameters:
      build_platform: x64
      build_configuration: Release
      version_suffix: '-CI'

  - template: /pipelines/templates/build-native-linux.yml@self
    parameters:
      build_platform: x64
      build_configuration: Debug
      version_suffix: '-CI'

  - template: /pipelines/templates/build-managed-linux.yml@self
    parameters:
      build_platform: x64
      build_configuration: Release
      version_suffix: '-CI'

  - template: /pipelines/templates/build-managed-linux.yml@self
    parameters:
      build_platform: x64
      build_configuration: Debug
      version_suffix: '-CI'
