# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

resources:
  pipelines:
  - pipeline: ADUDiffsDiffapiWindows
    source: ADU Diffs - diffapi windows
    trigger: true

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'build/diff-generation.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  diffgen_build_output: $(Build.SourcesDirectory)\src\managed\DiffGen\DiffGeneration\bin\$(buildConfiguration)\net6.0
  diffgen_tool_csproj:  $(Build.SourcesDirectory)\src\managed\DiffGen\tools\DiffGenTool\DiffGenTool.csproj
  diffgen_tool_build_output: $(Build.SourcesDirectory)\src\managed\DiffGen\tools\DiffGenTool\bin\$(buildConfiguration)\net6.0
  diffgen_tool_win64_output: $(diffgen_tool_build_output)\win-x64
  diffgen_tool_linux64_output: $(diffgen_tool_build_output)\linux-x64
  archiveutility_build_output: $(Build.SourcesDirectory)\src\managed\DiffGen\ArchiveUtility\bin\$(buildConfiguration)\net6.0
  cpioarchive_build_output: $(Build.SourcesDirectory)\src\managed\DiffGen\archives\CpioArchives\bin\$(buildConfiguration)\net6.0
  ext4archive_build_output: $(Build.SourcesDirectory)\src\managed\DiffGen\archives\Ext4Archives\bin\$(buildConfiguration)\net6.0
  swupdatearchive_build_output: $(Build.SourcesDirectory)\src\managed\DiffGen\archives\SWUpdateArchives\bin\$(buildConfiguration)\net6.0
  tararchive_build_output: $(Build.SourcesDirectory)\src\managed\DiffGen\archives\TarArchives\bin\$(buildConfiguration)\net6.0
  ERRORS_md_file: $(Build.SourcesDirectory)\src\managed\DiffGen\DiffGeneration\ERRORS.md
  diffgen_nuget_files_dir: $(Pipeline.Workspace)\diffgen-nuget-files
  major_version: '1'
  minor_version: '0'
  patch_version: '1'
  unittests_dir: $(Build.SourcesDirectory)\src\managed\DiffGen\tests\UnitTests\bin\$(buildConfiguration)\net6.0
  archiveutilitytest_dir: $(Build.SourcesDirectory)\src\managed\DiffGen\tests\ArchiveUtilityTest\bin\$(buildConfiguration)\net6.0
  tests_samples_dir: $(Build.SourcesDirectory)\src\managed\DiffGen\tests\samples

steps:
- task: CmdLine@
  displayName: 'Show Build Reason.'
  inputs:
    script: |
      echo Build.Reason: $(Build.Reason)
      echo resources.trigger: $(resources.triggeringAlias)
      echo resources.triggeringCategory: $(resources.triggeringCategory)

- task: CmdLine@2
  displayName: 'Show files'
  inputs:
    script: |
      echo showing: Build.SourcesDirectory ($(Build.SourcesDirectory))
      dir $(Build.SourcesDirectory) /s
      echo showing: Build.StagingDirectory ($(Build.StagingDirectory))
      dir $(Build.StagingDirectory) /s
      echo showing: Pipeline.Workspace ($(Pipeline.Workspace))
      dir $(Pipeline.Workspace) /s

- task: CredScan@2
  condition: succeededOrFailed()
  inputs:
    toolMajorVersion: 'V2'

- task: UseDotNet@2
  displayName: 'Use .NET Standard sdk'
  inputs:
    packageType: sdk
    version: 6.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DownloadPipelineArtifact@2
  displayName: 'Download Diff API drop - Windows'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '77999'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'drop'
    targetPath: $(diffgen_nuget_files_dir)

- task: DownloadPipelineArtifact@2
  displayName: 'Download tools from Diff API drop - Windows'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '77999'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'tools'
    targetPath: $(diffgen_nuget_files_dir)

- task: DownloadPipelineArtifact@2
  displayName: 'Download dumpextfs drop - Windows'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '77971'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'drop'
    targetPath: $(diffgen_nuget_files_dir)

- task: DownloadPipelineArtifact@2
  displayName: 'Download bsdiff drop - Windows'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '77984'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'drop'
    targetPath: $(diffgen_nuget_files_dir)

- task: DownloadPipelineArtifact@2
  displayName: 'Download dumpextfs - amd64 Linux'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '83676'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'drop'
    targetPath: $(diffgen_nuget_files_dir)

- task: DownloadPipelineArtifact@2
  displayName: 'Download libadudiffapi.so - amd64 Linux'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '80912'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'lib'
    targetPath: $(diffgen_nuget_files_dir)

- task: DownloadPipelineArtifact@2
  displayName: 'Download tools - amd64 Linux'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '80912'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'tools'
    targetPath: $(diffgen_nuget_files_dir)

- task: DownloadPipelineArtifact@2
  displayName: 'Download bsdiff drop - amd64 Linux'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '84687'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'drop'
    targetPath: $(diffgen_nuget_files_dir)

- task: CmdLine@2
  displayName: 'Copy ERRORS.md'
  inputs:
    script: copy /y $(ERRORS_md_file) $(diffgen_nuget_files_dir)

- task: CmdLine@2
  displayName: 'Show Diffgen Nuget files'
  inputs:
    script: |
      dir $(diffgen_nuget_files_dir)

- task: CmdLine@2
  displayName: 'Copy Nuget Files to UnitTests'
  inputs:
    script: |
      copy /y $(diffgen_nuget_files_dir) $(unittests_dir)

- task: CmdLine@2
  displayName: 'Show UnitTests files'
  inputs:
    script: |
      dir $(unittests_dir)

- task: CmdLine@2
  displayName: 'Show test sample files'
  inputs:
    script: |
      dir $(tests_samples_dir) /s

- task: VSTest@2
  inputs:
    platform: '$(buildplatform)'
    configuration: '$(buildconfiguration)'
    testAssemblyVer2: |
        $(unittests_dir)\UnitTests.dll
        $(archiveutilitytest_dir)\ArchiveUtilityTest.dll

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'ADU Diffs ESRP CodeSigning'
    FolderPath: '$(diffgen_build_output)'
    Pattern: '*.dll,*.exe'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "keyCode": "CP-230856",
          "operationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd sha256"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
    Region: 'PuertoRico'

- task: CmdLine@2
  displayName: 'Copy Built Binaries'
  inputs:
    script: |
      mkdir -p $(Build.ArtifactStagingDirectory)\libs
      copy /y $(diffgen_build_output)\*.dll $(Build.ArtifactStagingDirectory)\libs
      copy /y $(diffgen_build_output)\*.pdb $(Build.ArtifactStagingDirectory)\libs
      copy /y $(diffgen_build_output)\*.json $(Build.ArtifactStagingDirectory)\libs
      copy /y $(diffgen_build_output)\ArchiveUtility.dll $(archiveutility_build_output)
      copy /y $(diffgen_build_output)\CpioArchives.dll $(cpioarchive_build_output)
      copy /y $(diffgen_build_output)\Ext4Archives.dll $(ext4archive_build_output)
      copy /y $(diffgen_build_output)\SWUpdateArchives.dll $(swupdatearchive_build_output)
      copy /y $(diffgen_build_output)\TarArchives.dll $(tararchive_build_output)

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\libs'
    artifactType: 'pipeline'
    artifactName: 'libs'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'src\managed\DiffGen\DiffGeneration\DiffGeneration.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)\nuget'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(major_version)'
    minorVersion: '$(minor_version)'
    patchVersion: '$(patch_version)'
    basePath: '$(diffgen_nuget_files_dir)'
    includeReferencedProjects: true

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'ADU Diffs ESRP CodeSigning'
    FolderPath: '$(Build.ArtifactStagingDirectory)\nuget'
    Pattern: '*.nupkg'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetSign",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        },
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetVerify",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
    Region: 'PuertoRico'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\nuget'
    artifactType: 'pipeline'
    artifactName: 'drop'

- task: CmdLine@2
  displayName: 'Create Windows DiffGenTool drop'
  inputs:
    script: |
      dotnet publish $(diffgen_tool_csproj) --configuration $(buildConfiguration) --framework net6.0 --runtime win-x64 --self-contained false
      mkdir $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_tool_win64_output)\* $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\bsdiff.exe $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\bsdiff.dll $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\bspatch.exe $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\dumpextfs.exe $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\zstd_compress_file.exe $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\applydiff.exe $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\dumpdiff.exe $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\adudiffapi.dll $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\zstd.dll $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\zlib1.dll $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\NOTICE.txt $(Build.ArtifactStagingDirectory)\win-x64
      copy $(diffgen_nuget_files_dir)\LICENSE $(Build.ArtifactStagingDirectory)\win-x64

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\win-x64'
    artifactType: 'pipeline'
    artifactName: 'win64-diffgen-tool'

- task: CmdLine@2
  displayName: 'Create Linux DiffGenTool drop'
  inputs:
    script: |
      dotnet publish $(diffgen_tool_csproj) --configuration $(buildConfiguration) --framework net6.0 --runtime linux-x64 --self-contained false
      mkdir $(Build.ArtifactStagingDirectory)\linux-x64
      copy $(diffgen_tool_linux64_output)\* $(Build.ArtifactStagingDirectory)\linux-x64
      copy $(diffgen_nuget_files_dir)\bsdiff $(Build.ArtifactStagingDirectory)\linux-x64
      copy $(diffgen_nuget_files_dir)\bspatch $(Build.ArtifactStagingDirectory)\linux-x64
      copy $(diffgen_nuget_files_dir)\dumpextfs $(Build.ArtifactStagingDirectory)\linux-x64
      copy $(diffgen_nuget_files_dir)\zstd_compress_file $(Build.ArtifactStagingDirectory)\linux-x64
      copy $(diffgen_nuget_files_dir)\applydiff $(Build.ArtifactStagingDirectory)\linux-x64
      copy $(diffgen_nuget_files_dir)\dumpdiff $(Build.ArtifactStagingDirectory)\linux-x64      
      copy $(diffgen_nuget_files_dir)\libadudiffapi.so $(Build.ArtifactStagingDirectory)\linux-x64
      copy $(diffgen_nuget_files_dir)\NOTICE.txt $(Build.ArtifactStagingDirectory)\linux-x64
      copy $(diffgen_nuget_files_dir)\LICENSE $(Build.ArtifactStagingDirectory)\linux-x64      

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\linux-x64'
    artifactType: 'pipeline'
    artifactName: 'linux64-diffgen-tool'