trigger:
- main

pool:
  vmImage: ubuntu-latest

extends:
  template: bsdiff-template.yml
  parameters:
    vcpkg_triplet: x64-linux
    bootstrap_script: bootstrap-vcpkg.sh
    bsdiff_signing_location: $(Build.ArtifactStagingDirectory)/signing
    binary_extension: ''
    enable_sign: false
    copy_bsdiff_and_bz2_dll: false
