trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: 'build/diff-generation.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  diffgen_build_output: $(Build.SourcesDirectory)/src/managed/DiffGen/DiffGeneration/bin/$(buildConfiguration)/net5.0
  ERRORS_md_file: $(Build.SourcesDirectory)/src/managed/DiffGen/DiffGeneration/ERRORS.md
  diffgen_nuget_files_dir: $(Pipeline.Workspace)/diffgen-nuget-files
  major_version: '1'
  minor_version: '0'
  patch_version: '1'
  unittests_dir: $(Build.SourcesDirectory)/src/managed/DiffGen/tests/UnitTests
  unittests_output_dir: $(unittests_dir)/bin/$(buildConfiguration)/net5.0
  archiveutilitytest_dir: $(Build.SourcesDirectory)/src/managed/DiffGen/tests/ArchiveUtilityTest
  archiveutilitytest_output_dir: $(archiveutilitytest_dir)/bin/$(buildConfiguration)/net5.0
  tests_samples_dir: $(Build.SourcesDirectory)/src/managed/DiffGen/tests/samples
  packagesToPack: 'src/managed/DiffGen/DiffGeneration/DiffGeneration_linux.nuspec'

steps:
- bash: |
    echo showing Build.SourcesDirectory: $(Build.SourcesDirectory)
    ls $(Build.SourcesDirectory)
    echo showing Build.StagingDirectory: $(Build.StagingDirectory)
    ls $(Build.StagingDirectory)
    echo showing Pipeline.Workspace: $(Pipeline.Workspace)
    ls $(Pipeline.Workspace)
  displayName: 'Show files'

- bash: |
    sudo apt-get install -y bsdiff
    sudo apt-get install -y zstd
    sudo apt-get install -y nuget
  displayName: 'Install Dependencies'

- task: UseDotNet@2
  displayName: 'Use .NET Standard sdk'
  inputs:
    packageType: sdk
    version: 5.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    restoreArguments: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) -property:TargetOS=LINUX'

- task: DownloadPipelineArtifact@2
  displayName: 'Download dumpextfs'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '83676'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'drop'
    targetPath: $(diffgen_nuget_files_dir)

- task: DownloadPipelineArtifact@2
  displayName: 'Download libadudiffapi.so'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '80912'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'lib'
    targetPath: $(diffgen_nuget_files_dir)

- task: DownloadPipelineArtifact@2
  displayName: 'Download zstd_compress_file'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '80912'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'tools'
    targetPath: $(diffgen_nuget_files_dir)
    itemPattern: 'zstd_compress_file'

- task: DownloadPipelineArtifact@2
  displayName: 'Download bsdiff drop'
  inputs:
    buildType: 'specific'
    project: '6aaa0331-fb39-433f-a07a-2245a798c042'
    definition: '84687'
    buildVersionToDownload: 'latestFromBranch'
    branchName: $(Build.SourceBranch)
    artifactName: 'drop'
    targetPath: $(diffgen_nuget_files_dir)

- bash: |
    cp -f $(ERRORS_md_file) $(diffgen_nuget_files_dir)
  displayName: 'Copy ERRORS.md'

- bash: |
    cp -f $(ERRORS_md_file) $(diffgen_nuget_files_dir)
  displayName: 'Copy ERRORS.md'

- bash: |
    ls $(diffgen_nuget_files_dir)
  displayName: 'Show Diffgen Nuget files'

- bash: |
    cp -r -f $(diffgen_nuget_files_dir)/* $(unittests_output_dir)
    cp -r -f $(diffgen_nuget_files_dir)/* $(archiveutilitytest_output_dir)
  displayName: 'Copy Nuget Files to UnitTests'

- bash: |
    echo Dump of Files at: $(unittests_output_dir)
    ls $(unittests_output_dir)
    echo Dump of Files at: $(archiveutilitytest_output_dir)
    ls $(archiveutilitytest_output_dir)
  displayName: 'Show UnitTests files'

- bash: |
    chmod +x $(unittests_output_dir)/zstd_compress_file
    chmod +x $(unittests_output_dir)/dumpextfs
    chmod +x $(unittests_output_dir)/bsdiff
    chmod +x $(unittests_output_dir)/bspatch
    chmod +x $(archiveutilitytest_output_dir)/zstd_compress_file
    chmod +x $(archiveutilitytest_output_dir)/dumpextfs
    chmod +x $(archiveutilitytest_output_dir)/bsdiff
    chmod +x $(archiveutilitytest_output_dir)/bspatch
  displayName: 'Set access to test support binaries.'

- bash: |
    ls -R $(tests_samples_dir)
  displayName: 'Show test sample files'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: |
        $(unittests_dir)/UnitTests.csproj
        $(archiveutilitytest_dir)/ArchiveUtilityTest.csproj
    arguments: '--configuration $(buildConfiguration) -property:TargetOS=LINUX'

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'ADU Diffs ESRP CodeSigning'
    FolderPath: '$(diffgen_build_output)'
    Pattern: '*.dll'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "keyCode": "CP-230856",
          "operationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd sha256"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
    Region: 'PuertoRico'

- bash: |
    mkdir $(Build.ArtifactStagingDirectory)/libs
    cp -f $(diffgen_build_output)/*.dll $(Build.ArtifactStagingDirectory)/libs
    cp -f $(diffgen_build_output)/*.pdb $(Build.ArtifactStagingDirectory)/libs
    cp -f $(diffgen_build_output)/*.json $(Build.ArtifactStagingDirectory)/libs
  displayName: 'Copy Built Binaries'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/libs'
    artifactType: 'pipeline'
    artifactName: 'libs'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(packagesToPack)'
    packDestination: '$(Build.ArtifactStagingDirectory)/nuget'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(major_version)'
    minorVersion: '$(minor_version)'
    patchVersion: '$(patch_version)'
    basePath: '$(diffgen_nuget_files_dir)'
    includeReferencedProjects: true

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'ADU Diffs ESRP CodeSigning'
    FolderPath: '$(Build.ArtifactStagingDirectory)/nuget'
    Pattern: '*.nupkg'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetSign",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        },
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetVerify",
            "Parameters" : {},
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
    Region: 'PuertoRico'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/nuget'
    artifactType: 'pipeline'
    artifactName: 'drop'
