trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  dependencies: g++-9 libmhash-dev

extends:
  template: dumpextfs-template.yml
  parameters:
    build_script: build_vcpkg
    output_binary: dumpextfs
    vcpkg_triplet: x64-linux
    dependencies: $(dependencies)
