/**
 * @file error_codes.h
 *
 * @copyright Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 */
#pragma once

#include <cstdint>

namespace archive_diff::errors
{
enum class error_code : uint16_t
{
	none                       = 0,
	standard_library_exception = 1,

	hash_provider_initialization_failure  = 10000,
	hash_initialization_failure           = 10001,
	hash_data_failure                     = 10002,
	hash_get_value                        = 10003,
	hash_alg_to_bcrypt_alg_id             = 10004,
	hash_alg_id_to_algorithm_name         = 10005,
	hash_alg_to_gcrypt_algo               = 10006,
	hash_libgcrypt_initialization_failure = 10007,
	hash_failed_to_get_err_string         = 10008,

	io_reader_read_failure                                        = 20000,
	io_stream_read_error                                          = 20001,
	io_reader_slice_bound_error                                   = 20002,
	io_stored_blob_reader_read_offset                             = 20003,
	io_zlib_reader_seek_not_supported                             = 20100,
	io_zlib_reader_init_failed                                    = 20101,
	io_zlib_reader_already_initialized                            = 20102,
	io_zlib_state_not_ready                                       = 20103,
	io_zlib_reader_inflate_failed                                 = 20104,
	io_zlib_reader_no_more_data                                   = 20105,
	io_zlib_init_type_invalid                                     = 20106,
	io_zlib_writer_init_failed                                    = 20107,
	io_zlib_reader_deflate_failed                                 = 20108,
	io_zlib_too_much_data_processed                               = 20109,
	io_zlib_writer_deflate_failed                                 = 20110,
	io_zlib_writer_inflateEnd_failed                              = 20110,
	io_zstd_compressstream2_failed                                = 20200,
	io_zstd_decompress_stream_failed                              = 20201,
	io_zstd_decompress_cannot_finish                              = 20202,
	io_zstd_dictionary_too_large                                  = 20203,
	io_zstd_compress_cannot_finish                                = 20204,
	io_zstd_compress_stream_failed                                = 20205,
	io_zstd_compress_finished_early                               = 20206,
	io_zstd_decompress_finished_early                             = 20207,
	io_zstd_too_much_data_processed                               = 20208,
	io_binary_file_reader_failed_open                             = 20300,
	io_temp_file_readerwriter_failed_open                         = 20301,
	io_binary_file_writer_failed_open                             = 20302,
	io_child_reader_parent_is_null                                = 20400,
	io_child_reader_out_of_bounds                                 = 20401,
	io_sequential_reader_bad_offset                               = 20500,
	io_sequential_write_bad_offset                                = 20600,
	io_chained_reader_not_enough_data                             = 20700,
	io_chained_reader_offset_in_reader_past_size                  = 20701,
	io_producer_consumer_reader_writer_invalid_offset             = 20800,
	io_producer_consumer_reader_writer_writing_when_done          = 20801,
	io_producer_consumer_reader_writer_reading_too_much_available = 20802,
	io_stored_blob_reader_factory_too_large                       = 20900,
	io_temp_file_tmpfile_failed                                   = 21000,
	io_chain_reader_skipping_too_much                             = 21100,
	io_chain_offset_mismatch                                      = 21101,
	io_chain_read_too_much                                        = 21102,
	io_chain_bad_offset                                           = 21103,
	io_chain_read_nothing                                         = 21104,
	io_device_new_end_past_size                                   = 21200,

	diff_magic_header_wrong                                 = 30000,
	diff_version_wrong                                      = 30001,
	diff_read_diff_size_mismatch                            = 30002,
	diff_bad_hash_type                                      = 30003,
	diff_archive_item_missing_recipe                        = 30004,
	diff_inline_asset_byte_count_mismatch                   = 30005,
	diff_remainder_offset_too_large                         = 30006,
	diff_remainder_length_too_large                         = 30007,
	diff_cannot_delete_file                                 = 30008,
	diff_verify_hash_failure                                = 30009,
	diff_invalid_recipe_type                                = 30010,
	diff_chunk_count_too_large                              = 30011,
	diff_write_chunk_at_unexpected_offset                   = 30012,
	diff_write_incorrect_inline_assets                      = 30013,
	diff_dump_nested_delta_item_missing_recipe              = 30014,
	diff_dump_nested_delta_item_not_inline_asset            = 30015,
	diff_dump_parameter_invalid_type                        = 30016,
	diff_remainder_chunk_length_too_large                   = 30015,
	diff_inline_asset_offset_too_large                      = 30016,
	diff_inline_asset_length_too_large                      = 30017,
	diff_cannot_add_implicit_offset                         = 30018,
	diff_cannot_add_implicit_length                         = 30019,
	diff_remainder_chunk_offset_too_large                   = 30020,
	diff_invalid_recipe_parameter_type                      = 30100,
	diff_recipe_parameter_read_invalid_type                 = 30101,
	diff_recipe_parameter_invalid_type_for_apply            = 30102,
	diff_recipe_parameter_invalid_type_for_get_number_value = 30103,
	diff_recipe_invalid_parameter_count                     = 30104,
	diff_recipe_parameter_count_too_large                   = 30105,
	diff_recipe_invalid_recipe_index                        = 30106,
	diff_recipe_parameter_out_of_bounds                     = 30107,
	diff_copy_source_offset_too_large                       = 30200,
	diff_copy_source_length_too_large                       = 30201,
	diff_region_offset_too_large                            = 30300,
	diff_region_length_too_large                            = 30301,
	diff_zstd_number_parameter_too_large                    = 30400,
	diff_recipe_zstd_decompression_not_supported            = 30401,
	diff_invalid_compression_context_type                   = 30500,
	diff_no_way_to_make_source_reader                       = 30600,
	diff_no_way_to_make_nested_source_reader                = 30601,
	diff_all_zero_length_too_large                          = 30700,
	diff_recipe_gz_decompression_recipe_not_supported       = 30800,
	diff_bspatch_failure                                    = 30900,
	diff_bspatch_cannot_open_target                         = 30901,
	diff_zstd_apply_failure                                 = 31000,
	diff_zstd_cannot_open_target                            = 31001,
	diff_verify_source_size_mismatch                        = 31100,
	diff_blob_cache_bad_blobdef_for_sequential_reader       = 31200,
	diff_recipe_host_invalid_recipe_id                      = 31300,
	diff_recipe_host_unsupported_recipe_name                = 31301,
	diff_slicing_invalid_state                              = 31400,
	diff_slicing_no_stored_item                             = 31401,
	diff_slicing_no_slices_requested                        = 31402,
	diff_slicing_request_slice_overlap                      = 31403,
	diff_slicing_request_slice_no_hash                      = 31404,
	diff_slicing_request_size_too_large                     = 31405,
	diff_slicing_produced_hash_mismatch                     = 31406,
	diff_slicing_no_requests_for_slice                      = 31407,
	diffs_kitchen_item_not_ready_to_fetch                   = 31500,
	diffs_kitchen_no_selected_recipes                       = 31501,
	diffs_prepared_item_kitchen_gone                        = 31600,
	diffs_prepared_item_wrong_kind                          = 31601,
	diffs_prepared_visit_no_result                          = 31602,
	diffs_prepared_item_unkown                              = 31603,

	recipe_chain_item_and_recipe_mismatch   = 31700,
	recipe_chain_total_item_length_mismatch = 31701,
	recipe_zstd_compression_not_supported   = 31702,
	recipe_slice_cannot_slice_temp_file_item = 31703,

	item_definition_hash_size_mismatch             = 32000,
	item_definition_hash_same_type_different_value = 32001,
	item_definition_no_sha256_hash                 = 32002,

	recipe_zlib_compression_level_invalid = 33000,

	api_could_not_delete_file        = 40000,
	api_unexpected_hash_type         = 40001,
	api_unexpected_archive_item_type = 40002,
	api_unexpected_recipe_type       = 40003,
	api_already_finalized            = 40004,
};
}
